<?php

// Includes
include "player.class.php";
include "team.class.php";
include "real_team.class.php";
include "competition.class.php";
include "group.class.php";
include "lineup.class.php";
include "match.class.php";
include "round.class.php";
include "result.class.php";
include "user.class.php";
include "fantacalcio.block.inc";
include "fantacalcio.tooltip.inc";
include "fantacalcio.cron.inc";

define("COMPETITION_TYPE_SD", 1);
define("COMPETITION_TYPE_GP", 2);
define("DATA_SOURCE_URL", "http://fantacalciocircus.altervista.org");

$roles_long = array(t("Portiere"), t("Difensore"), t("Centrocampista"), t("Attaccante"));
$roles = array(t("P"), t("D"), t("C"), t("A"));
$GLOBALS["roles_long"] = $roles_long;
$GLOBALS["roles"] = $roles;
$GLOBALS["rounds_status"] = array("-1" => t("Risultati provvisori"), "0" => t("Non giocata"), "1" => t("Giocata"), 
"2" => t("Congelata"), "3" => t("Saltata") );
$GLOBALS["providers"] = array("1" => "Milano", "2" => "Roma", "3" => "Napoli", "4" => "Italia" );

// Css file
// drupal_add_css('sites/all/modules/fantacalcio/css/style.css', 'themes', 'all', TRUE);

// init
function fantacalcio_init() {
  global $user;
  
  variable_set("fantacalcio_user_can_create_team", true);
  
//   drupal_add_js(base_path() . drupal_get_path("module", "fantacalcio") . "/components/lightbox/bootstrap-lightbox.min.js");
//   drupal_add_js("jQuery(document).delegate('*[data-toggle=\"lightbox\"]', 'click', function(event) {
//     event.preventDefault();
//     jQuery(this).ekkoLightbox();
// });",  array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));
//   drupal_add_js("jQuery('[data-toggle=\"lightbox\"]').lightbox()",  array('type' => 'inline', 'scope' => 'footer', 'weight' => 5));
  
  drupal_add_css('http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css', array(
    'group' => CSS_DEFAULT, 
    'every_page' => TRUE, 
    'type' => 'external'));
  drupal_add_css(base_path() . drupal_get_path("module", "fantacalcio") . "/css/fantacalcio.css", array(
    'group' => CSS_DEFAULT, 
    'every_page' => TRUE, 
    'type' => 'external'));
//   drupal_add_css(base_path() . drupal_get_path("module", "fantacalcio") . "/components/lightbox/bootstrap-lightbox.min.css", array(
//     'group' => CSS_DEFAULT, 
//     'every_page' => TRUE, 
//     'type' => 'external'));
  
  if ($user->uid > 0 && !isset($user->groups)) {

    $teams = Team::allByUser($user->uid);
    $user->teams = $teams;
    
    $groups = array();
    if (count($teams) > 0) {
      
      $query = db_select("fanta_teams_groups", "tg");
      $query->join("fanta_groups", "g", "tg.g_id = g.g_id");
      $query->condition("tg.t_id", array_keys($teams), "IN");
      $query->fields("g");
      
      $result = $query->execute();
      
      foreach($result as $row) {
        if (!isset($groups[$row->c_id]))
          $groups[$row->c_id] = array();
       //$groups[$row->c_id] = array(); 
        array_push($groups[$row->c_id], $row->g_id);
      }
    }
    
    $user->groups = $groups;
    // t_id
    // $result = (db_query("SELECT t_id FROM {fanta_teams} WHERE active = 1 AND uid = :t_id", array(
    // ":t_id" => $user->uid
    // )));
    // $t_id = $result->fetchObject()->t_id;
    
    // if ($t_id) {
    // $user->t_id = $t_id;
    
    // $sql = "SELECT * FROM {fanta_groups} WHERE active = 1";
    // $result = db_query($sql);
    // foreach ( $result as $row ) {
    // $competitions [$row->g_id] = $row;
    // }
    
    // $sql = "SELECT g_id FROM {fanta_teams_groups} WHERE active = 1 AND t_id = :t_id";
    // $result = db_query($sql, array(
    // ":t_id" => $t_id
    // ));
    // foreach ( $result as $row ) {
    // $user->groups [$competitions [$row->g_id]->c_id] = $competitions [$row->g_id];
    // }
    // }
  }
}

function fantacalcio_user_login(&$edit, $account) {
  
  fantacalcio_check_role($account);
}

function fantacalcio_check_role($account) { 
  // controllo variabile
  if (variable_get("fantacalcio_assign_default_role", 0)) { 
    //watchdog("fantacalcio", t("%team: Acquisto di %player (-%quotation crediti)"), array("%team" => $team->name, "%player" => $player->name, "%quotation" => $player->getQuotation()), WATCHDOG_INFO);
    if (!in_array($account->roles, "coach") && user_role_load_by_name('coach') != null) {
      $user_roles = $account->roles;
      $user_roles[] = 'coach';
      
      module_invoke('user', 'save', $account, array('roles' => $user_roles));
    }
  }
}

// help
function fantacalcio_help($section = '', $arg) {
  $output = '';
  switch ($section) {
    case "admin/modules#description" :
      $output = t("Gestisce una lega di Fantacalcio");
      break;
    case "admin/help#fantacalcio" :
      $output = t("Gestisce una lega di Fantacalcio");
      break;
  }
  return $output;
}

// permessi
function fantacalcio_permission() {
  return array(
    'access content fantacalcio' => array(
      'title' => 'access content fantacalcio'), 
    'administer team' => array('title' => 'administer team'), 
    'administer draft' => array('title' => 'administer draft'), 
    'administer fantacalcio' => array('title' => 'administer fantacalcio'), 
    );
}

// menu
function fantacalcio_menu() {
  $items = array();
  
  $items['home'] = array(
    'title' => 'Home', 
    'page callback' => 'fantacalcio_home', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.home.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['classifica'] = array(
    'title' => 'Classifica', 
    'page callback' => 'fantacalcio_standings', 
    'page arguments' => array(1, 2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.standings.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['calendario'] = array(
    'title' => 'Calendario', 
    'page callback' => 'fantacalcio_calendar', 
    'page arguments' => array(1), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.calendar.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['calendario/%/%'] = array(
    'title' => 'Calendario', 
    'page callback' => 'fantacalcio_calendario_round', 
    'page arguments' => array(1, 2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.calendar.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['main/classifica'] = array(
    'title' => t('Classifica'), 
    'page callback' => 'fantacalcio_main_league_standings', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.realteams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['main/calendario'] = array(
    'title' => 'Calendario', 
    'page callback' => 'fantacalcio_main_league_calendar', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.realteams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie'] = array(
    'title' => t('Gestione squadre'), 
    'page callback' => 'fantacalcio_teams_manager', 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie/%'] = array(
    'title' => t('Gestione squadre'), 
    'page callback' => 'fantacalcio_team_manager', 
    'page arguments' => array(1), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie/add'] = array(
    'title' => t('Aggiungi squadra'), 
    'page callback' => 'fantacalcio_team_manager_add', 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie/%/dati'] = array(
    'title' => t('Gestione squadre'), 
    'page callback' => 'fantacalcio_team_manager', 
    'page arguments' => array(1), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie/%/movimenti'] = array(
    'title' => t('Gestione squadre'), 
    'page callback' => 'fantacalcio_squad_edit', 
    'page arguments' => array(1), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie/%/rosa'] = array(
    'title' => t('Gestione squadre'), 
    'page callback' => 'fantacalcio_show_squad', 
    'page arguments' => array(1), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie/%/lista-movimenti'] = array(
    'title' => t('Gestione squadre'), 
    'page callback' => 'fantacalcio_squad_movements', 
    'page arguments' => array(1), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie/%/movimenti/buy/%'] = array(
    'title' => t('Gestione squadre'), 
    'page callback' => 'fantacalcio_buy_player_ajax', 
    'page arguments' => array(1, 4), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie/%/movimenti/sell/%'] = array(
    'title' => t('Gestione squadre'), 
    'page callback' => 'fantacalcio_sell_player_ajax', 
    'page arguments' => array(1, 4), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni'] = array(
    'title' => 'Formazioni', 
    'page callback' => '_fantacalcio_lineup', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/multe'] = array(
    'title' => 'Multe', 
    'page callback' => 'fantacalcio_show_payments', 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/view'] = array(
    'title' => 'Formazioni', 
    'page callback' => '_fantacalcio_lineup_view', 
    'page arguments' => array(2, 3, 4), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/box'] = array(
    'title' => 'Formazioni', 
    'page callback' => '_fantacalcio_lineup_box', 
    'page arguments' => array(2, 3, 4), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/insert'] = array(
    'title' => 'Inserisci Formazione', 
    'page callback' => 'fantacalcio_lineup_insert_start', 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/insert/%'] = array(
    'title' => 'Inserisci Formazione', 
    'page callback' => 'fantacalcio_lineup_insert_start', 
    'page arguments' => array(2), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/insert/%/%'] = array(
    'title' => 'Inserisci Formazione', 
    'page callback' => 'fantacalcio_lineup_insert_start', 
    'page arguments' => array(2, 3), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/insert/%/%/penalties'] = array(
    'title' => 'Ordina Rigoristi', 
    'page callback' => 'fantacalcio_insert_penalties', 
    'page arguments' => array(2, 3), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/admin'] = array(
    'title' => 'Amministra Formazioni', 
    'page callback' => 'fantacalcio_admin_lineup', 
    'page arguments' => array(2, 3), 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/admin/penalties'] = array(
    'title' => 'Amministra Rigoristi', 
    'page callback' => 'fantacalcio_admin_penalties', 
    'page arguments' => array(3, 4), 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/validate'] = array(
    'title' => 'Valida Formazione', 
    'page callback' => 'fantacalcio_formazione_validate', 
    'page arguments' => array(2, 3), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['risultati'] = array(
    'title' => 'Risultati', 
    'page callback' => 'fantacalcio_results', 
    'page arguments' => array(1), 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.results.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['risultati/%'] = array(
    'title' => 'Risultati', 
    'page callback' => 'fantacalcio_results', 
    'page arguments' => array(1, 2), 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.results.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['squadre'] = array(
    'title' => 'Squadre', 
    'page callback' => 'fantacalcio_show_teams', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['team/js'] = array(
    'title' => 'JSON', 
    'description' => 'Dati ahah', 
    'page callback' => 'fantacalcio_team_form_ahah', 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['updateformazione'] = array(
    'title' => 'update formazione', 
    'page callback' => 'fantacalcio_update_formazione', 
    'page arguments' => array(1, 2, 3, 4), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['updateformazioneadmin'] = array(
    'title' => 'update formazione', 
    'page callback' => 'fantacalcio_update_formazione_admin', 
    'page arguments' => array(1, 2, 3, 4, 5), 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['updatecompetitionround'] = array(
    'title' => 'update competition round', 
    'page callback' => 'fantacalcio_update_competition_round', 
    'page arguments' => array(1, 2, 3), 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['calendario/partita/%'] = array(
    'title' => 'Scheda Partita', 
    'page callback' => 'show_match_details', 
    
    'page arguments' => array(2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.calendar.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['scheda/partita'] = array(
    'title' => 'Scheda Partita', 
    'page callback' => 'show_match_details', 
    'page arguments' => array(2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.calendar.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche'] = array(
    'title' => 'Statistiche', 
    'page callback' => 'stats_home', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.general.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/giocatori-liberi'] = array(
    'title' => 'Giocatori Liberi', 
    'page callback' => 'fantacalcio_free_players', 
    'page arguments' => array(2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.players.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/players'] = array(
    'title' => 'Statistiche Giocatori', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('choose_players_stats'), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.players.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/players/%/%/%/%/%'] = array(
    'title' => 'Statistiche Giocatori', 
    'page callback' => 'players_stats', 
    'page arguments' => array(2, 3, 4, 5, 6), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.players.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/giocatore'] = array(
    'title' => 'Statistiche Giocatore', 
    'page callback' => 'player_details', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.players.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/giocatore/%'] = array(
    'title' => 'Statistiche Giocatore', 
    'page callback' => 'player_details', 
    'page arguments' => array(2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.players.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['scheda/giocatore/%'] = array(
    'title' => 'Statistiche Giocatore', 
    'page callback' => 'player_stats', 
    'page arguments' => array(2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.players.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/squadra'] = array(
    'title' => 'Statistiche Squadra', 
    'page callback' => 'team_stats', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/generali'] = array(
    'title' => 'Statistiche Generali', 
    'page callback' => 'statistiche_generali', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.general.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/grafici'] = array(
    'title' => 'Grafici', 
    'page callback' => 'statistiche_grafici', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.charts.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/grafici/%/%/%/%'] = array(
    'title' => 'Grafici', 
    'page callback' => 'statistiche_crea_grafico', 
    'page arguments' => array(2, 3, 4, 5), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.charts.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/grafici/chart/%/%/%/%'] = array(
    'title' => 'Grafici', 
    'page callback' => 'statistiche_crea_grafico', 
    'page arguments' => array(3, 4, 5, 6), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.charts.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/topflop'] = array(
    'title' => 'Top / Flop', 
    'page callback' => 'statistiche_topflop', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.topflop.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/topflop/%'] = array(
    'title' => 'Top / Flop', 
    'page callback' => 'statistiche_topflop', 
    'page arguments' => array(2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.topflop.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/topflop-all'] = array(
    'title' => 'Top / Flop', 
    'page callback' => 'statistiche_topflop_all', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.topflop.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/topflop-all/%'] = array(
    'title' => 'Top / Flop', 
    'page callback' => 'statistiche_topflop_all', 
    'page arguments' => array(2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.topflop.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/topflop/%/%'] = array(
    'title' => 'Top / Flop', 
    'page callback' => 'statistiche_topflop', 
    'page arguments' => array(2, 3), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.topflop.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/autocomplete/players'] = array(
    'title' => 'Statistiche Generali', 
    'page callback' => 'statistiche_autocomplete_players', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.players.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  

  $items['mercato']  = array(
      'title' => t('Mercato'),
      'page callback' => 'fantamercato_group',
      'access arguments' => array('administer draft'),
      'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.draft.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mercato/group']  = array(
      'title' => t('Mercato'),
      'page callback' => 'fantamercato_group',
      'access arguments' => array('administer draft'),
      'type' => MENU_CALLBACK,
      'file' => 'fantacalcio.draft.inc',
      'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mercato/group/%']  = array(
      'title' => t('Mercato'),
      'page callback' => 'fantamercato_group',
      'page arguments' => array(2),
      'access arguments' => array('administer draft'),
      'type' => MENU_CALLBACK,
      'file' => 'fantacalcio.draft.inc',
      'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mercato/team']  = array(
      'title' => t('Mercato'),
      'page callback' => 'fantamercato_team',
      'access arguments' => array('administer draft'),
      'type' => MENU_CALLBACK,
      'file' => 'fantacalcio.draft.inc',
      'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mercato/team/%/%']  = array(
      'title' => t('Mercato'),
      'page callback' => 'fantamercato_team',
      'page arguments' => array(2, 3),
      'access arguments' => array('administer draft'),
      'type' => MENU_CALLBACK,
      'file' => 'fantacalcio.draft.inc',
      'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mercato/swaps']  = array(
      'title' => t('Mercato'),
      'page callback' => 'fantamercato_swaps',
      'access arguments' => array('administer draft'),
      'type' => MENU_CALLBACK,
      'file' => 'fantacalcio.draft.inc',
      'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mercato/swaps/%']  = array(
      'title' => t('Mercato'),
      'page callback' => 'fantamercato_swaps',
      'page arguments' => array(2),
      'access arguments' => array('administer draft'),
      'type' => MENU_CALLBACK,
      'file' => 'fantacalcio.draft.inc',
      'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mercato/view']  = array(
      'title' => t('Mercato'),
      'page callback' => 'fantamercato_view',
      'access arguments' => array('access content fantacalcio'),
      'type' => MENU_CALLBACK,
      'file' => 'fantacalcio.draft.inc',
      'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mercato/view/%']  = array(
      'title' => t('Mercato'),
      'page callback' => 'fantamercato_view',
      'page arguments' => array(2),
      'access arguments' => array('access content fantacalcio'),
      'type' => MENU_CALLBACK,
      'file' => 'fantacalcio.draft.inc',
      'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mercato/autocomplete/group/%']  = array(
      'title' => 'Autocomplete giocatori',
      'page callback' => 'fantamercato_autocomplete_players_group',
      'page arguments' => array(3),
      'access arguments' => array('administer draft'),
      'type' => MENU_CALLBACK,
      'file' => 'fantacalcio.draft.inc',
      'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mercato/autocomplete/team/%/%']  = array(
      'title' => 'Autocomplete giocatori',
      'page callback' => 'fantamercato_autocomplete_players_team',
      'page arguments' => array(3, 4),
      'access arguments' => array('administer draft'),
      'type' => MENU_CALLBACK,
      'file' => 'fantacalcio.draft.inc',
      'file path' => drupal_get_path('module', 'fantacalcio')
  );
  
  $items['mercato/autocomplete/swaps/%']  = array(
      'title' => 'Autocomplete giocatori',
      'page callback' => 'fantamercato_autocomplete_players_swaps',
      'page arguments' => array(3),
      'access arguments' => array('administer draft'),
      'type' => MENU_CALLBACK,
      'file' => 'fantacalcio.draft.inc',
      'file path' => drupal_get_path('module', 'fantacalcio'));
  
  /*
   * // Registration and login pages.
   * $items['user'] = array(
   * 'title' => 'User account',
   * 'title callback' => 'user_menu_title',
   * 'page callback' => 'user_page',
   * 'access callback' => TRUE,
   * 'file' => 'user.pages.inc',
   * 'weight' => -10,
   * 'menu_name' => 'user-menu',
   * );
   *
   * $items['user/login'] = array(
   * 'title' => 'Log in',
   * 'access callback' => 'user_is_anonymous',
   * 'type' => MENU_DEFAULT_LOCAL_TASK,
   * );
   *
   * $items['user/register'] = array(
   * 'title' => 'Create new account',
   * 'page callback' => 'drupal_get_form',
   * 'page arguments' => array('user_register_form'),
   * 'access callback' => 'user_register_access',
   * 'type' => MENU_LOCAL_TASK,
   * );
   *
   * $items['user/password'] = array(
   * 'title' => 'Request new password',
   * 'page callback' => 'drupal_get_form',
   * 'page arguments' => array('user_pass'),
   * 'access callback' => TRUE,
   * 'type' => MENU_LOCAL_TASK,
   * 'file' => 'user.pages.inc',
   * );
   */
  
  $items['admin/fantacalcio'] = array(
    'title' => t('Fantacalcio'), 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_settings'), 
    'access arguments' => array('administer fantacalcio'), 
    'description' => 'Gestione di una lega di Fantacalcio.', 
    'file' => 'fantacalcio.admin.inc', 
    'type' => MENU_NORMAL_ITEM, 
    'file path' => drupal_get_path('module', 'fantacalcio'), 
    'weight' => -1);
  
  $items['admin/fantacalcio/general'] = array(
    'title' => t('Generale'), 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_DEFAULT_LOCAL_TASK, 
    'weight' => -1);
  
  $items['admin/fantacalcio/users'] = array(
    'title' => t('Utenti'), 
    'page callback' => 'fantacalcio_admin_users_list', 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_LOCAL_TASK, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/users/add'] = array(
    'title' => t('Utenti'), 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array("fantacalcio_admin_user_add_form"), 
    'access arguments' => array('administer fantacalcio'), 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/users/%'] = array(
    'title' => t('Utenti'), 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array("fantacalcio_admin_user_form", 3), 
    'access arguments' => array('administer fantacalcio'), 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/teams'] = array(
    'title' => t('Fantasquadre'), 
    'page callback' => 'fantacalcio_admin_teams_list', 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_LOCAL_TASK, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/teams/%'] = array(
    'title' => t('Fantasquadre'), 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_team', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/teams/%/delete'] = array(
    'title' => t('Fantasquadre'), 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_team_delete', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/groups'] = array(
    'title' => 'Gironi', 
    'page callback' => 'fantacalcio_admin_groups_list', 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_LOCAL_TASK, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/groups/%'] = array(
    'title' => 'Gironi', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_group', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/groups/%/delete'] = array(
    'title' => 'Gironi', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_group_delete', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/competitions'] = array(
    'title' => 'Competizioni', 
    'page callback' => 'fantacalcio_admin_competitions_list', 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_LOCAL_TASK, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/competitions/%'] = array(
    'title' => 'Competizioni', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_competition', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/competitions/%/delete'] = array(
    'title' => 'Competizioni', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_competition_delete', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/competitions/%/rounds'] = array(
    'title' => 'Giornate Competizione', 
    'page callback' => 'fantacalcio_admin_competition_rounds', 
    'page arguments' => array(4), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));


  $items['admin/fantacalcio/realteams'] = array(
    'title' => t('Squadre'), 
    'page callback' => 'fantacalcio_admin_real_teams_list', 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_LOCAL_TASK, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/realteams/%'] = array(
    'title' => t('Squadre'), 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_real_team', 3), 
    'access arguments' => array('administer fantacalcio'), 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/realteams/%/delete'] = array(
    'title' => t('Squadre'), 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_real_team_delete', 3), 
    'access arguments' => array('administer fantacalcio'), 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));

  $items['admin/fantacalcio/realteams/import'] = array(
    'title' => t('Importa squadre'), 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_real_teams_list_import'), 
    'access arguments' => array('administer fantacalcio'), 
    'weight' => 1, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));

  
  $items['admin/fantacalcio/matches'] = array(
    'title' => 'Partite', 
    'page callback' => 'fantacalcio_admin_matches', 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_LOCAL_TASK, 
    'weight' => 10, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/matches/%'] = array(
    'title' => 'Partite', 
    'page callback' => 'fantacalcio_admin_matches', 
    'page arguments' => array(4), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/matches/%/%'] = array(
    'title' => 'Partite', 
    'page callback' => 'fantacalcio_admin_matches', 
    'page arguments' => array(4, 5), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/matches/%/%/add'] = array(
    'title' => 'Partite', 
    'page callback' => 'fantacalcio_admin_matches', 
    'page arguments' => array(4, 5, 6), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/matches/%/delete'] = array(
    'title' => 'Partite', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_match_delete', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/matches/%/calendar'] = array(
    'title' => 'Calendario Gironi', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_matches_calendar', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/rounds'] = array(
    'title' => 'Giornate', 
    'page callback' => 'fantacalcio_admin_rounds_list', 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_LOCAL_TASK, 
    'weight' => 9, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/rounds/%'] = array(
    'title' => 'Giornate', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_round', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/rounds/%/delete'] = array(
    'title' => 'Giornate', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_round_delete', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));

 $items['admin/fantacalcio/rounds/import'] = array(
    'title' => t('Importa giornate'), 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_rounds_list_import'), 
    'access arguments' => array('administer fantacalcio'), 
    'weight' => 1, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/players'] = array(
    'title' => 'Giocatori', 
    'page callback' => 'fantacalcio_admin_players_list', 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_LOCAL_TASK, 
    'weight' => 15, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/players/%'] = array(
    'title' => 'Lista Giocatori', 
    'page callback' => 'fantacalcio_admin_players_list_player', 
    'page arguments' => array(3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_LOCAL_TASK,
    'weight' => 0, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/players/list'] = array(
    'title' => 'Aggiorna Lista', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_players_list_update'), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_LOCAL_TASK,
    'weight' => 1, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/players/add'] = array(
    'title' => 'Aggiungi giocatore', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_players_add_form'), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_LOCAL_TASK,
    'weight' => 1, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
     
  return $items;
}

// Blocks
function fantacalcio_block_info() {
  $blocks['user_summary'] = array(
      // The name that will appear in the block list.
      'info' => t('User summary'),
      // Default setting.
      'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  $blocks['competition_summary'] = array(
      // The name that will appear in the block list.
      'info' => t('Competition summary'),
      // Default setting.
      'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  $blocks['wall_last_messages'] = array(
      // The name that will appear in the block list.
      'info' => t('Wall'),
      // Default setting.
      'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  return $blocks;
}

function fantacalcio_block_view($delta = '') {
  
  switch ($delta) {
    case 'user_summary' :
      $block['subject'] = fantacalcio_block_user_summary_title();
      $block['content'] = fantacalcio_block_user_summary();
      break;
    case 'competition_summary' :
      $block['subject'] = t('Competition summary');
      $block['content'] = fantacalcio_block_competition_summary();
      break;
    case 'wall_last_messages' :
      $block['subject'] = t('Wall');
      $block['content'] = fantacalcio_block_last_wall_messages();
      break;
  }
  return $block;
  
}

// cron
function fantacalcio_cron() {
  
  $vote_round = Round::getNext();
  $round = Round::getByRound($vote_round);

  if (variable_get("fantacalcio_automatic_updates", 0)) {

  //status giocatori
  Player::updateStatus();
  
  //giornate
  $rounds_dates = json_decode(file_get_contents(DATA_SOURCE_URL . "/rounds/rounds.json"));
  foreach ($rounds_dates as $_round => $round_date) {
    db_update("fanta_rounds")->fields(array("date" => $round_date->date, "end_date" => $round_date->date))->condition("round", $_round)->condition("status", "1", "!=")->execute();

  }

  $matches = json_decode(file_get_contents(DATA_SOURCE_URL . "/matches/" . $round->round . ".json"));

  if (isset($matches->data) && count($matches->data) > 0) {
    $dates = array_map(function ($item){ return $item->date;}, $matches->data);
    $start = min($dates);
    $start -= variable_get('fantacalcio_round_advance_minutes', '0') * 60;
    $end = max($dates) + 5 * 3600; //5 ore dopo l'inizio dell'ultima partita
    $round->updateDates($start, $end);

    watchdog('fantacalcio', t('Date aggiornate per la giornata: %round'), array('%round' => $round->round), WATCHDOG_NOTICE);

    $round = Round::getByRound($vote_round);

  }

  //calcola risultati 
  if (time() > $round->end_date && $round->status_id != 1)
    fantacalcio_cron_calculate_results($round->round);

  }

  //promemoria formazioni
  $reminder_hours = variable_get("fantacalcio_lineups_reminder_hours", 0);
  if ($reminder_hours > 0 && time() > ($round->date - ($reminder_hours * 3600)) && $round->reminder_sent == false)
    fantacalcio_create_lineups_reminder($round); 
}

// theme functions
function fantacalcio_theme($existing, $type, $theme, $path) {
  return array(
    'fantacalcio_formazione_mobile_form' => array(
      'arguments' => array('form' => NULL)), 
    'fantacalcio_update_matches' => array(
      'arguments' => array("form" => NULL)), 
    'fantacalcio_add_matches' => array(
      'arguments' => array("form" => NULL)), 
    'fantacalcio_admin_players_list_player' => array('render element' => 'form'), 
    'fantacalcio_admin_round' => array('render element' => 'form'), 
    'team_buy_player' => array('render element' => 'form'),
    'group_buy_player' => array('render element' => 'form'),
    'fantacalcio_admin_matches_calendar' => array('render element' => 'form'), 
    'fantastats_choose_stats_form' => array('render element' => 'form'), 
    'team' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-team'), 
    'columns' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-columns'), 
    'movements' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-squad-edit'), 
    'movements-list' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-movements-list'), 
    'squad' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-squad'), 
    'team_form' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-team-form'), 
    'standings' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-tabs'), 
    'calendar' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-calendar'), 
    'main_calendar' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-main-calendar'), 
    'group_tabs' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-tabs'), 
    'lineup-view' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-competitions-tabs'), 
    'lineup-insert' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-lineup-insert'));
}

function fantacalcio_check_value($value) {
  if ($value)
    return "<i class='fa fa-check-circle text-success'></i>";
  else
    return "<i class='fa fa-minus-circle text-danger'></i>";
}

function fantacalcio_show_role($role) {
  return "<span class=\"fa-stack\">
					<i class=\"fa fa-square fa-stack-2x squad-player-role-" . $role . "\"></i>
					<i class=\"fa fa-stack-1x\" style=\"color: white;\"><span class=\"font-normal\">" . Player::convertRole($role) . "</span></i>
				</span>";
}

function fantacalcio_show_status($name, $team, $player_status) {
    
  $status_class = fantacalcio_get_status_classes($player_status->status, $player_status->position);
  
  if ($player_status->status == "ok") {
    $position = $player_status->position == 1 ? t("Titolare") : t("Riserva");
  $content = "<p>" . $player_status->match . "</p>";
    $content .= "<table class=\"table\"><tr><th>Posizione probabile:</th><td>" . $position ."</td></tr><tr><th>Probabilità di giocare:</th><td>" . $player_status->percent . "%</td></tr></table><i class=\"caption\">Ultimo aggiornamento: " . date("d-m-Y H:i", $player_status->updated) . "</i>";
  }
  else {
    switch ($player_status->status) {
      case "injured":
        $status = "Infortunato";
        break;
      case "suspended":
        $status = "Squalificato";
        break;
      case "not_found":
        $status = "Non trovato";
        break;
    }
    
    $content = "<table class=\"table\"><tr><th>Stato:</th><td>" . $status . "</td></tr></table><i class=\"caption\">Ultimo aggiornamento: " . date("d-m-Y H:i", $player_status->updated) . "</i>";
  }
  
  $out = "<a tabindex='0' role='button' data-trigger='focus' data-toggle='popover' data-placement='top' title='" . $name . " (" . $team . ")" 
. "' data-content='" . $content 
. "' data-html='" . true 
. "'>";
  
  $out .= "<i class='fa fa-lg fa-circle " . $status_class . "'></i>";
  
  $out .= "</a>";
  
  return $out;
  
}

function fantacalcio_get_status_classes($status, $status_position) {
  switch($status) {
    case "injured":
      return "text-danger";
      break;
    case "suspended":
      return "text-danger";
      break;
    case "not_found":
      return "text-danger";
      break;
    case "ok":
      return $status_position == 1 ? "text-success" : "text-warning";
      break;
  }
}

function fantacalcio_show_cards($yellow, $red) {
  if ($yellow == 1)
    return "<i class='fa fa-lg fa-square' style='color:#EE3; transform: scale(0.75, 1);'></i>";
  elseif ($red == 1)
  return "<i class='fa fa-lg fa-square' style='color:#D33; transform: scale(0.75, 1);'></i>";
  else
    return "";
}

