<?php

// Includes

/*
 * include "fantacalcio.common.inc";
 * include "fantacalcio.admin.inc";
 * include "fantacalcio.teams.inc";
 * include "fantacalcio.calendar.inc";
 * include "fantacalcio.standings.inc";
 * include "fantacalcio.lineups.inc";
 * include "fantacalcio.results.inc";
 * include 'fantacalcio.stats.general.inc';
 * include 'fantacalcio.stats.teams.inc';
 * include 'fantacalcio.stats.images.inc';
 * include 'fantacalcio.stats.topflop.inc';
 * include 'fantacalcio.stats.players.inc';
 * include "fantacalcio.home.inc";
 * include "fantacalcio.block.inc";
 * include "fantacalcio.curl.inc";
 */
include "player.class.php";
include "team.class.php";
include "real_team.class.php";
include "competition.class.php";
include "group.class.php";
include "lineup.class.php";
include "match.class.php";
include "round.class.php";
include "user.class.php";
// include "fantacalcio.common.inc";
include "fantacalcio.block.inc";
include "fantacalcio.tooltip.inc";

define("COMPETITION_TYPE_SD", 1);
define("COMPETITION_TYPE_GP", 2);
define("DATA_SOURCE_URL", "http://fantacalciocircus.altervista.org");

// Css file
// drupal_add_css('sites/all/modules/fantacalcio/css/style.css', 'themes', 'all', TRUE);

// init
function fantacalcio_init() {
  global $user;
  
  variable_set("fantacalcio_user_can_create_team", true);
  
  drupal_add_css('http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css', array(
    'group' => CSS_DEFAULT, 
    'every_page' => TRUE, 
    'type' => 'external'));
  drupal_add_css(base_path() . drupal_get_path("module", "fantacalcio") . "/css/fantacalcio.css", array(
    'group' => CSS_DEFAULT, 
    'every_page' => TRUE, 
    'type' => 'external'));
  
  if ($user->uid > 0 && !isset($user->groups)) {
    
    // t_id
    // $result = (db_query("SELECT t_id FROM {fanta_teams} WHERE active = 1 AND uid = :t_id", array(
    // ":t_id" => $user->uid
    // )));
    // $t_id = $result->fetchObject()->t_id;
    
    // if ($t_id) {
    // $user->t_id = $t_id;
    
    // $sql = "SELECT * FROM {fanta_groups} WHERE active = 1";
    // $result = db_query($sql);
    // foreach ( $result as $row ) {
    // $competitions [$row->g_id] = $row;
    // }
    
    // $sql = "SELECT g_id FROM {fanta_teams_groups} WHERE active = 1 AND t_id = :t_id";
    // $result = db_query($sql, array(
    // ":t_id" => $t_id
    // ));
    // foreach ( $result as $row ) {
    // $user->groups [$competitions [$row->g_id]->c_id] = $competitions [$row->g_id];
    // }
    // }
  }
}

function fantacalcio_user_login(&$edit, $account) {
  
  fantacalcio_check_role($account);
}

function fantacalcio_check_role($account) { 
  watchdog("fantacalcio", "BBB", array(), WATCHDOG_NOTICE);
  // controllo variabile
  if (variable_get("fantacalcio_assign_default_role", 0)) { 
    watchdog("fantacalcio", "AAA", array(), WATCHDOG_NOTICE);
    //watchdog("fantacalcio", t("%team: Acquisto di %player (-%quotation crediti)"), array("%team" => $team->name, "%player" => $player->name, "%quotation" => $player->getQuotation()), WATCHDOG_INFO);
    if (!in_array($account->roles, "coach") && user_role_load_by_name('coach') != null) {
      $user_roles = $account->roles;
      $user_roles[] = 'coach';
      
      module_invoke('user', 'save', $account, array('roles' => $user_roles));
    }
  }
  else watchdog("fantacalcio", "BBB", array(), WATCHDOG_NOTICE);
}
// help
function fantacalcio_help($section = '', $arg) {
  $output = '';
  switch ($section) {
    case "admin/modules#description" :
      $output = t("Gestisce una lega di Fantacalcio");
      break;
    case "admin/help#fantacalcio" :
      $output = t("Gestisce una lega di Fantacalcio");
      break;
  }
  return $output;
}

// permessi
function fantacalcio_permission() {
  return array(
    'access content fantacalcio' => array(
      'title' => 'access content fantacalcio'), 
    'administer team' => array('title' => 'administer team'), 
    'administer fantacalcio' => array('title' => 'administer fantacalcio'), 
    );
}

// menu
function fantacalcio_menu() {
  $items = array();
  
  $items['home'] = array(
    'title' => 'Home', 
    'page callback' => 'fantacalcio_home', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.home.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['classifica'] = array(
    'title' => 'Classifica', 
    'page callback' => 'fantacalcio_standings', 
    'page arguments' => array(1, 2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.standings.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['calendario'] = array(
    'title' => 'Calendario', 
    'page callback' => 'fantacalcio_calendar', 
    'page arguments' => array(1), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.calendar.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['calendario/%/%'] = array(
    'title' => 'Calendario', 
    'page callback' => 'fantacalcio_calendario_round', 
    'page arguments' => array(1, 2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.calendar.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['main/classifica'] = array(
    'title' => t('Classifica'), 
    'page callback' => 'fantacalcio_main_league_standings', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.realteams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['main/calendario'] = array(
    'title' => 'Calendario', 
    'page callback' => 'fantacalcio_main_league_calendar', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.realteams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie'] = array(
    'title' => t('Gestione squadre'), 
    'page callback' => 'fantacalcio_teams_manager', 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie/%'] = array(
    'title' => t('Gestione squadre'), 
    'page callback' => 'fantacalcio_team_manager', 
    'page arguments' => array(1), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie/add'] = array(
    'title' => t('Aggiungi squadra'), 
    'page callback' => 'fantacalcio_team_manager_add', 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie/%/dati'] = array(
    'title' => t('Gestione squadre'), 
    'page callback' => 'fantacalcio_team_manager', 
    'page arguments' => array(1), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie/%/movimenti'] = array(
    'title' => t('Gestione squadre'), 
    'page callback' => 'fantacalcio_squad_edit', 
    'page arguments' => array(1), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie/%/rosa'] = array(
    'title' => t('Gestione squadre'), 
    'page callback' => 'fantacalcio_show_squad', 
    'page arguments' => array(1), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie/%/lista-movimenti'] = array(
    'title' => t('Gestione squadre'), 
    'page callback' => 'fantacalcio_squad_movements', 
    'page arguments' => array(1), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie/%/movimenti/buy/%'] = array(
    'title' => t('Gestione squadre'), 
    'page callback' => 'fantacalcio_buy_player_ajax', 
    'page arguments' => array(1, 4), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['mie/%/movimenti/sell/%'] = array(
    'title' => t('Gestione squadre'), 
    'page callback' => 'fantacalcio_sell_player_ajax', 
    'page arguments' => array(1, 4), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni'] = array(
    'title' => 'Formazioni', 
    'page callback' => '_fantacalcio_lineup', 
    'access arguments' => array('access fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/multe'] = array(
    'title' => 'Multe', 
    'page callback' => 'fantacalcio_show_multe', 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/view'] = array(
    'title' => 'Formazioni', 
    'page callback' => '_fantacalcio_lineup_view', 
    'page arguments' => array(2, 3, 4), 
    'access arguments' => array('access fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/box'] = array(
    'title' => 'Formazioni', 
    'page callback' => '_fantacalcio_lineup_box', 
    'page arguments' => array(2, 3, 4), 
    'access arguments' => array('access fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/insert'] = array(
    'title' => 'Inserisci Formazione', 
    'page callback' => 'fantacalcio_lineup_insert_start', 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/insert/%'] = array(
    'title' => 'Inserisci Formazione', 
    'page callback' => 'fantacalcio_lineup_insert_start', 
    'page arguments' => array(2), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/insert/%/%'] = array(
    'title' => 'Inserisci Formazione', 
    'page callback' => 'fantacalcio_lineup_insert_start', 
    'page arguments' => array(2, 3), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/insert/%/penalties'] = array(
    'title' => 'Inserisci Rigoristi', 
    'page callback' => 'fantacalcio_insert_penalties', 
    'page arguments' => array(2), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/admin'] = array(
    'title' => 'Amministra Formazioni', 
    'page callback' => 'fantacalcio_admin_lineup', 
    'page arguments' => array(2, 3), 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/admin/penalties'] = array(
    'title' => 'Amministra Rigoristi', 
    'page callback' => 'fantacalcio_admin_penalties', 
    'page arguments' => array(3, 4), 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['formazioni/validate'] = array(
    'title' => 'Valida Formazione', 
    'page callback' => 'fantacalcio_formazione_validate', 
    'page arguments' => array(2, 3), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['risultati'] = array(
    'title' => 'Risultati', 
    'page callback' => 'fantacalcio_results', 
    'page arguments' => array(1), 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.results.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['risultati/%'] = array(
    'title' => 'Risultati', 
    'page callback' => 'fantacalcio_results', 
    'page arguments' => array(1, 2), 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.results.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['squadre'] = array(
    'title' => 'Squadre', 
    'page callback' => 'fantacalcio_show_teams', 
    'access arguments' => array('access fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['giocatori/liberi'] = array(
    'title' => 'Giocatori Liberi', 
    'page callback' => 'fantacalcio_giocatori_liberi', 
    'page arguments' => array(2), 
    'access arguments' => array('access fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.players.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['team/js'] = array(
    'title' => 'JSON', 
    'description' => 'Dati ahah', 
    'page callback' => 'fantacalcio_team_form_ahah', 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['updateformazione'] = array(
    'title' => 'update formazione', 
    'page callback' => 'fantacalcio_update_formazione', 
    'page arguments' => array(1, 2, 3, 4), 
    'access arguments' => array('administer team'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['updateformazioneadmin'] = array(
    'title' => 'update formazione', 
    'page callback' => 'fantacalcio_update_formazione_admin', 
    'page arguments' => array(1, 2, 3, 4, 5), 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.lineups.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['updatecompetitionround'] = array(
    'title' => 'update competition round', 
    'page callback' => 'fantacalcio_update_competition_round', 
    'page arguments' => array(1, 2, 3), 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['calendario/partita/%'] = array(
    'title' => 'Scheda Partita', 
    'page callback' => 'show_match_details', 
    
    'page arguments' => array(2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.calendar.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['scheda/partita'] = array(
    'title' => 'Scheda Partita', 
    'page callback' => 'show_match_details', 
    'page arguments' => array(2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.calendar.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche'] = array(
    'title' => 'Statistiche', 
    'page callback' => 'stats_home', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.general.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/players'] = array(
    'title' => 'Statistiche Giocatori', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('choose_players_stats'), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.players.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/players/%/%/%/%/%'] = array(
    'title' => 'Statistiche Giocatori', 
    'page callback' => 'players_stats', 
    'page arguments' => array(2, 3, 4, 5, 6), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.players.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/giocatore'] = array(
    'title' => 'Statistiche Giocatore', 
    'page callback' => 'dettagli_giocatore', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.players.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/giocatore/%'] = array(
    'title' => 'Statistiche Giocatore', 
    'page callback' => 'dettagli_giocatore', 
    'page arguments' => array(2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.players.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['scheda/giocatore/%'] = array(
    'title' => 'Statistiche Giocatore', 
    'page callback' => 'scheda_giocatore', 
    'page arguments' => array(2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.players.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/squadra'] = array(
    'title' => 'Statistiche Squadra', 
    'page callback' => 'team_stats', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.teams.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/generali'] = array(
    'title' => 'Statistiche Generali', 
    'page callback' => 'statistiche_generali', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.general.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/grafici'] = array(
    'title' => 'Grafici', 
    'page callback' => 'statistiche_grafici', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.charts.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/grafici/%/%/%/%'] = array(
    'title' => 'Grafici', 
    'page callback' => 'statistiche_crea_grafico', 
    'page arguments' => array(2, 3, 4, 5), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.charts.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/grafici/chart/%/%/%/%'] = array(
    'title' => 'Grafici', 
    'page callback' => 'statistiche_crea_grafico', 
    'page arguments' => array(3, 4, 5, 6), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.charts.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/topflop'] = array(
    'title' => 'Top / Flop', 
    'page callback' => 'statistiche_topflop', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.topflop.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/topflop/%'] = array(
    'title' => 'Top / Flop', 
    'page callback' => 'statistiche_topflop_round', 
    'page arguments' => array(2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.topflop.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/topflop-all'] = array(
    'title' => 'Top / Flop', 
    'page callback' => 'statistiche_topflop_all', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.topflop.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/topflop-all/%'] = array(
    'title' => 'Top / Flop', 
    'page callback' => 'statistiche_topflop_all_round', 
    'page arguments' => array(2), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.topflop.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/topflop/%/%'] = array(
    'title' => 'Top / Flop', 
    'page callback' => 'statistiche_topflop_round_team', 
    'page arguments' => array(2, 3), 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.topflop.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['statistiche/autocomplete/players'] = array(
    'title' => 'Statistiche Generali', 
    'page callback' => 'statistiche_autocomplete_players', 
    'access arguments' => array('access content fantacalcio'), 
    'type' => MENU_NORMAL_ITEM, 
    'file' => 'fantacalcio.stats.players.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  /*
   * // Registration and login pages.
   * $items['user'] = array(
   * 'title' => 'User account',
   * 'title callback' => 'user_menu_title',
   * 'page callback' => 'user_page',
   * 'access callback' => TRUE,
   * 'file' => 'user.pages.inc',
   * 'weight' => -10,
   * 'menu_name' => 'user-menu',
   * );
   *
   * $items['user/login'] = array(
   * 'title' => 'Log in',
   * 'access callback' => 'user_is_anonymous',
   * 'type' => MENU_DEFAULT_LOCAL_TASK,
   * );
   *
   * $items['user/register'] = array(
   * 'title' => 'Create new account',
   * 'page callback' => 'drupal_get_form',
   * 'page arguments' => array('user_register_form'),
   * 'access callback' => 'user_register_access',
   * 'type' => MENU_LOCAL_TASK,
   * );
   *
   * $items['user/password'] = array(
   * 'title' => 'Request new password',
   * 'page callback' => 'drupal_get_form',
   * 'page arguments' => array('user_pass'),
   * 'access callback' => TRUE,
   * 'type' => MENU_LOCAL_TASK,
   * 'file' => 'user.pages.inc',
   * );
   */
  
  $items['admin/fantacalcio'] = array(
    'title' => t('Fantacalcio'), 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_settings'), 
    'access arguments' => array('administer fantacalcio'), 
    'description' => 'Gestione di una lega di Fantacalcio.', 
    'file' => 'fantacalcio.admin.inc', 
    'type' => MENU_NORMAL_ITEM, 
    'file path' => drupal_get_path('module', 'fantacalcio'), 
    'weight' => -1);
  
  $items['admin/fantacalcio/general'] = array(
    'title' => t('Generale'), 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_DEFAULT_LOCAL_TASK, 
    'weight' => -1);
  
  $items['admin/fantacalcio/users'] = array(
    'title' => t('Utenti'), 
    'page callback' => 'fantacalcio_admin_users_list', 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_LOCAL_TASK, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/users/add'] = array(
    'title' => t('Utenti'), 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array("fantacalcio_admin_user_add_form"), 
    'access arguments' => array('administer fantacalcio'), 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/users/%'] = array(
    'title' => t('Utenti'), 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array("fantacalcio_admin_user_form", 3), 
    'access arguments' => array('administer fantacalcio'), 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/teams'] = array(
    'title' => t('Squadre'), 
    'page callback' => 'fantacalcio_admin_teams_list', 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_LOCAL_TASK, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/teams/%'] = array(
    'title' => t('Squadre'), 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_team', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/teams/%/delete'] = array(
    'title' => t('Squadre'), 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_team_delete', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/groups'] = array(
    'title' => 'Gironi', 
    'page callback' => 'fantacalcio_admin_groups_list', 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_LOCAL_TASK, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/groups/%'] = array(
    'title' => 'Gironi', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_group', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/groups/%/delete'] = array(
    'title' => 'Gironi', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_group_delete', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/competitions'] = array(
    'title' => 'Competizioni', 
    'page callback' => 'fantacalcio_admin_competitions_list', 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_LOCAL_TASK, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/competitions/%'] = array(
    'title' => 'Competizioni', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_competition', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/competitions/%/delete'] = array(
    'title' => 'Competizioni', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_competition_delete', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/competitions/%/rounds'] = array(
    'title' => 'Giornate Competizione', 
    'page callback' => 'fantacalcio_admin_competition_rounds', 
    'page arguments' => array(4), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/matches'] = array(
    'title' => 'Partite', 
    'page callback' => 'fantacalcio_admin_matches', 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_LOCAL_TASK, 
    'weight' => 10, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/matches/%'] = array(
    'title' => 'Partite', 
    'page callback' => 'fantacalcio_admin_matches', 
    'page arguments' => array(4), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/matches/%/%'] = array(
    'title' => 'Partite', 
    'page callback' => 'fantacalcio_admin_matches', 
    'page arguments' => array(4, 5), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/matches/%/%/add'] = array(
    'title' => 'Partite', 
    'page callback' => 'fantacalcio_admin_matches', 
    'page arguments' => array(4, 5, 6), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/matches/%/delete'] = array(
    'title' => 'Partite', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_match_delete', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/matches/%/calendar'] = array(
    'title' => 'Calendario Gironi', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_matches_calendar', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/rounds'] = array(
    'title' => 'Giornate', 
    'page callback' => 'fantacalcio_admin_rounds_list', 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_LOCAL_TASK, 
    'weight' => 9, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/rounds/%'] = array(
    'title' => 'Giornate', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_round', 4), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/rounds/%/delete'] = array(
    'title' => 'Giornate', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_round_delete', 3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_NORMAL_ITEM,
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/players'] = array(
    'title' => 'Giocatori', 
    'page callback' => 'fantacalcio_admin_players_list', 
    'access arguments' => array('administer fantacalcio'), 
    'type' => MENU_LOCAL_TASK, 
    'weight' => 15, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/players/%'] = array(
    'title' => 'Lista Giocatori', 
    'page callback' => 'fantacalcio_admin_players_list_player', 
    'page arguments' => array(3), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_LOCAL_TASK,
    'weight' => 0, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/players/list'] = array(
    'title' => 'Aggiorna Lista', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_players_list_update'), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_LOCAL_TASK,
    'weight' => 1, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
  
  $items['admin/fantacalcio/players/add'] = array(
    'title' => 'Aggiungi giocatore', 
    'page callback' => 'drupal_get_form', 
    'page arguments' => array('fantacalcio_admin_players_add_form'), 
    'access arguments' => array('administer fantacalcio'), 
    
    // 'type' => MENU_LOCAL_TASK,
    'weight' => 1, 
    'file' => 'fantacalcio.admin.inc', 
    'file path' => drupal_get_path('module', 'fantacalcio'));
     
  return $items;
}

// Blocks
function fantacalcio_block($op = 'list', $delta = 0) {
  if (user_access('access content')) {
    if ($op == 'list') {
      $blocks[0]['info'] = 'Riepilogo';
      $blocks[1]['info'] = 'LastNews';
      $blocks[2]['info'] = 'Wall';
      $blocks[3]['info'] = 'LastRss';
      $blocks[4]['info'] = 'Situation';
      $blocks[5]['info'] = 'Countdown';
      $blocks[6]['info'] = 'Risultati provvisori';
      return $blocks;
    }
    elseif ($op == 'view') {
      switch ($delta) {
        case 0 :
          $block['subject'] = 'Riepilogo';
          $block['content'] = fantacalcio_block_riepilogo();
          break;
        case 1 :
          $block['subject'] = 'LastNews';
          $block['content'] = home_last_blog_post(5);
          break;
        case 2 :
          $block['subject'] = 'Wall';
          $block['content'] = home_last_wall_messages(10);
          break;
        case 3 :
          $block['subject'] = 'LastRss';
          $block['content'] = home_last_rss_news(5);
          break;
        case 4 :
          $block['subject'] = 'Situation';
          $block['content'] = fantacalcio_home_situation();
          break;
        case 5 :
          $block['subject'] = 'Countdown';
          $block['content'] = fantacalcio_block_countdown();
          break;
        case 6 :
          $block['subject'] = 'Risultati provvisori';
          $block['content'] = fantacalcio_block_risultati_provvisori();
          break;
      }
      return $block;
    }
  }
}

// cron
function fantacalcio_cron() {
  include "fantacalcio.cron.inc";
  // fantacalcio_send_formazioni_email();
  // fantacalcio_results();
}

// theme functions
function fantacalcio_theme($existing, $type, $theme, $path) {
  return array(
    'fantacalcio_formazione_mobile_form' => array(
      'arguments' => array('form' => NULL)), 
    'fantacalcio_update_matches' => array(
      'arguments' => array("form" => NULL)), 
    'fantacalcio_add_matches' => array(
      'arguments' => array("form" => NULL)), 
    'fantacalcio_admin_players_list_player' => array('render element' => 'form'), 
    'fantacalcio_admin_round' => array(
      'arguments' => array("form" => NULL)), 
    'insert_penalties_form' => array(
      'arguments' => array("form" => NULL)), 
    'fantacalcio_admin_matches_calendar' => array('render element' => 'form'), 
    'fantastats_choose_stats_form' => array(
      'arguments' => array('form' => NULL)), 
    'team' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-team'), 
    'columns' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-columns'), 
    'movements' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-squad-edit'), 
    'movements-list' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-movements-list'), 
    'squad' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-squad'), 
    'team_form' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-team-form'), 
    'standings' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-tabs'), 
    'calendar' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-calendar'), 
    'group_tabs' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-tabs'), 
    'lineup-view' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-competitions-tabs'), 
    'lineup-insert' => array(
      'render element' => 'elements', 
      'template' => 'templates/page-lineup-insert'));
}

function _fantacalcio_home() {
  return "";
}

function fantacalcio_check_value($value) {
  if ($value)
    return "<i class='fa fa-check-circle text-success'></i>";
  else
    return "<i class='fa fa-minus-circle text-danger'></i>";
}